server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_database?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
# swagger-ui custom path
springdoc:
  swagger-ui:
    path : /swagger-ui.html


oss:
  accessKey: yourAccessKey
  secretKey: yourSecretKey
  bucket: hnlg-blog
